#!/bin/bash
##current working directory
cwdir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
##color codes for -e
colors() {
DIM='\033[2m' BOLD='\033[0m\033[1m' NORM='\033[0m\033[2m' CLS='\033[0m' BRED='\033[0;91m' RED='\033[0;31m' BGREEN='\033[0;92m' GREEN='\033[0;32m' BPURPLE='\033[0;95m' ORANGE='\033[0;33m' BLUE='\033[0;94m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
}
##msgn replaces echo -n
msgn() {
echo >&2 -ne "${1-}"
}
##msg replaces echo
msg() {
echo >&2 -e "${1-}"
}
##get the colors
colors
