#!/bin/bash
##B.Thompson
##header and footer
basehead () {
echo "read: https://wiki.archlinux.org/title/installation_guide"
echo "Goal: A linux [VM] desktop [$awin]."
}

sleepspin () {
stime=15
sspin=0
swheel='-\|/'
sback=' '
smax=$(( $stime * 10 ))
while [ $sspin -le $smax ]
do
sspin=$(( $sspin + 1 ))
if [ $sspin -le $smax ]; then
siter=$(( (siter+1) %4 ))
echo -ne "\b${swheel:$siter:1}"
else
echo -ne "\b$sback"
fi
sleep .10
done
}

umountall () {
if [ "$apext" = "true" ]; then
umount "$rmnt/$hmnt" || umount -f "$rmnt/$hmnt" || umount -l "$rmnt/$hmnt"
umount "$rmnt/$fpmnt" || umount -f "$rmnt/$fpmnt" || umount -l "$rmnt/$fpmnt"
fi

umount "$rmnt/$bmnt" || umount -f "$rmnt/$bmnt" || umount -l "$rmnt/$bmnt"
umount "$rmnt" || umount -f "$rmnt" || umount -l "$rmnt"
swapoff "$rdev$spar"
}

basefoot () {
if [ "$areboot" = "true" ]; then
clear
fi
msg "${BPURPLE}$osn is Finished!${CLS}"
if [ "$warn" = "true" ]; then
msg "Sys:${BOLD}[$osn] ${CLS}Host:${BOLD}[$ahost]${CLS} User:${BOLD}[$auser]${CLS} Pass:${BOLD}[$apass]${CLS}"
aline
fi
msg "${BOLD}Things to do:${CLS}"
echo "Use 'flatpak search <term>' to find more apps, or flats <term>"
echo "Batch install flatpak apps using lists with flatiset.sh"
aline
msg "${BOLD}Boot housekeeping:${CLS}"
echo "Change your boot order OR remove the media OR hit [F12]"
echo "OR select 'Boot existing OS' from the Arch ISO boot menu"
if [ "$areboot" = "true" ]; then
stime=15
msgn "${BRED}Rebooting${CLS} in $stime seconds. ${GREEN}"
sleepspin
reboot
else
if [ "$warn" = "true" ]; then
aline
msg "${BGREEN}reboot${CLS}"
fi
aline
fi
}
