#!/bin/bash
##B.Thompson
##regen and extra tasks
regen () {
##regen linux/user
echo -n "Regenerating linux/env/$auser..."
(userdel -r "$auser" > /dev/null 2>&1) && echo -n "."
sleep .5 && echo -n "."
useradd -m "$auser" && echo -n "."
((echo $apass; echo $apass) | passwd $auser > /dev/null 2>&1) && echo -n "."
(mkinitcpio -p linux > /dev/null 2>&1) && echo ".okay."
##boot image
if [ -d "$bbdir" ]; then
cp "$bbdir"/Butterfly.jpg "/$bmnt/$awall"
fi
##get xfce4 going or not...
if [ "$awm" = "false" ]; then
rm "$ahome/.profile"
rm "/etc/skel/.profile"
else
touch "$ahome"/.Xauthority
touch "$ahome"/.xinitrc
fi
}

icrypt () {
echo -n "Cloning $capp [crypt tool]..."
cd "$apkg"
(git clone https://aur.archlinux.org/$capp.git > /dev/null 2>&1) && echo ".okay."
echo -n "build/install $capp..."
cd "$apkg/$capp"
chown -R "$auser" "$apkg/$capp"
(su $auser -c "makepkg -si --noconfirm" > /dev/null 2>&1) && echo ".okay."
ccrypt -e -K "$apass" "$idir/$aconf" #ccrypt the conf file with the apass password
chmod 0700 "$idir"
}

issh () {
##ssh key
if [ "$sshkey" = "true" ]; then
(scp -rp "$sshhost":~/.ssh ~/ > /dev/null 2>&1)
fi
}

reman () {
##gen/update man pages
echo -n "Updating man pages..."
mandb -q 2> /tmp/man$$.err
echo "...Done!"
}

