#!/bin/bash
##B.Thompson
##regen and extra tasks
regen () {
##regen linux/user
echo -n "Regenerating linux+env..."
(userdel -r "$auser" > /dev/null 2>&1) && echo -n "."
sleep .5 && echo -n "."
((mkinitcpio -p linux > /dev/null 2>&1) && echo ".okay.") || echo "mkinitcpio -p linux failed!"
##boot image
if [ -d "$bbdir" ]; then
cp "$bbdir"/Butterfly.jpg "/$bmnt/$awall"
fi
if [ "$pbon" = "true" ]; then
msg "${YELLOW}Interactive install ${BOLD}$pbon${YELLOW}, $auser will be created after reboot; login as root.${CLS}"
touch ~/.firstboot
echo 'if [ -f ~/.firstboot ]; then
homectl create '"$auser"' --disk-size='"$pbds"' --uid='"$pbuid"' --fs-type='"$afs"' --auto-resize-mode=off
chown -R '"$auser"' '"$aloc"'
echo "login as '"$auser"' when complete."
echo "Reconfiguring packages per sets..."
rmpacset.sh rlist.set
flatiset.sh googlezoom.set
rm ~/.firstboot
exit
else
cp /etc/skel/.profile .
fi' > ~/.profile
else
echo -n "Regenerating user [$auser]..."
useradd -m "$auser" && echo -n "."
((echo $apass; echo $apass) | passwd $auser > /dev/null 2>&1) && echo -n "."
chown -R "$auser" "$aloc"
echo ".okay."
fi
}
icrypt () {
echo -n "Cloning crypt tool [$capp]..."
cd "$apkg"
(git clone https://aur.archlinux.org/$capp.git > /dev/null 2>&1) && echo ".okay."
echo -n "build/install [$capp]..."
cd "$apkg/$capp"
chown -R "$auser" "$apkg/$capp"
(su $auser -c "makepkg -si --noconfirm" > /dev/null 2>&1) && echo ".okay."
ccrypt -e -K "$apass" "$idir/$aconf" #ccrypt the conf file with the apass password
chmod 0700 "$idir"
}
issh () {
##ssh key
if [ "$sshkey" = "true" ]; then
(scp -rp "$sshhost":~/.ssh ~/ > /dev/null 2>&1)
fi
}
reman () {
##gen/update man pages
echo -n "Updating man pages..."
mandb -q 2> /tmp/man$$.err
echo ".okay."
}
