#!/bin/bash

regen () {
##regen linux
echo -n "Regenerating linux/os/$auser..."
(userdel -r "$auser" > /dev/null 2>&1) && echo -n "."
sleep .5 && echo -n "."
useradd -m "$auser" && echo -n "."
((echo $apass; echo $apass) | passwd $auser > /dev/null 2>&1) && echo -n "."
(mkinitcpio -p linux > /dev/null 2>&1) && echo ".okay."
touch /home/$auser/.xinitrc
touch /home/$auser/.Xauthority
}

icrypt () {
echo -n "Cloning $capp [crypt tool]..."
cd "$apkg"
(git clone https://aur.archlinux.org/$capp.git > /dev/null 2>&1) && echo ".okay."
echo -n "build/install $capp..."
cd "$apkg/$capp"
chown -R "$auser" "$apkg/$capp"
(su $auser -c "makepkg -si --noconfirm" > /dev/null 2>&1) && echo ".okay."
ccrypt -e -K "$apass" "$idir/$aconf" #ccrypt the conf file with the apass password
}

issh () {
##ssh key
if [ "$sshkey" = "true" ]; then
(scp -rp "$sshhost":~/.ssh ~/ > /dev/null 2>&1)
fi
}

reman () {
##gen/update man pages
echo -n "Updating man pages..."
mandb -q 2> /tmp/man$$.err
echo "...Done!"
}

afoot () {
#set $auser admin and msg
chown -R "$auser" "$aloc"
chmod 0700 "$idir"
echo "$osn is okay."
echo "Things to do:"
echo "Use 'flatpak search <term>' to find more apps."
echo "Change themes in xfce with: darkxfce.sh or litexfce.sh"
aline
echo "Boot housekeeping:"
echo "Change your boot order OR remove the media OR hit [F12]"
echo "OR select 'Boot existing OS' from the Arch ISO boot menu"
}

